force-app/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <displayFormat>COM-{00000}</displayFormat>
        <label>Commission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Sales_Agent__c.field-meta.xml
<CustomField>
    <fullName>Sales_Agent__c</fullName>
    <label>Sales Agent</label>
    <referenceTo>Sales_Agent__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Agent__c/Sales_Agent__c.object-meta.xml
<CustomObject>
    <label>Sales Agent</label>
    <nameField>
        <label>Sales Agent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Agent__c/fields/Completed_Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Completed_Commission_Amount__c</fullName>
    <label>Completed Commission Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Agent__c/fields/Default_Rate__c.field-meta.xml
<CustomField>
    <fullName>Default_Rate__c</fullName>
    <label>Default Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHelperTest.cls
@IsTest
public with sharing class OpportunityTriggerHelperTest {
    @TestSetup 
    static void setup(){
        Account account = new Account(Name='Jhon Doe');
        insert account;

        Opportunity opportunity = new Opportunity();
        opportunity.Name = 'Jhon Doe';
        opportunity.AccountId = account.Id;
        opportunity.StageName = 'New';
        opportunity.Amount = 1000;
        opportunity.CloseDate = System.today()+10;
        insert opportunity;

        Sales_Agent__c agent = new Sales_Agent__c();
        agent.Default_Rate__c = 5;
        agent.Name = 'Will Smith';
        insert agent;

        Commission__c commission = new Commission__c();
        commission.Opportunity__c = opportunity.Id;
        commission.Sales_Agent__c = agent.Id;
        commission.Rate__c = 7;
        insert commission;
    }

    @IsTest 
    static void testUpdateOpportunity() {
        Test.startTest();
        Opportunity opportunity = [SELECT Id, StageName FROM Opportunity WHERE Name = 'Jhon Doe' LIMIT 1];
        opportunity.StageName = 'Completed Won';
        update opportunity;
        Sales_Agent__c agent = [SELECT Completed_Commission_Amount__c FROM Sales_Agent__c WHERE Name = 'Will Smith'];
        System.assertEquals(70, agent.Completed_Commission_Amount__c, 'Agent does not have the correct commission.');
        Test.stopTest();
    }
}