force-app/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <displayFormat>COM-{00000}</displayFormat>
        <label>Commission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Sales_Agent__c.field-meta.xml
<CustomField>
    <fullName>Sales_Agent__c</fullName>
    <label>Sales Agent</label>
    <referenceTo>Sales_Agent__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Agent__c/Sales_Agent__c.object-meta.xml
<CustomObject>
    <label>Sales Agent</label>
    <nameField>
        <label>Sales Agent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Agent__c/fields/Completed_Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Completed_Commission_Amount__c</fullName>
    <label>Completed Commission Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Agent__c/fields/Pending_Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pending_Commission_Amount__c</fullName>
    <label>Pending Commission Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHelper.cls
public with sharing class OpportunityTriggerHelper {
    public static void updateOpportunity(Map<Id, Opportunity> opportunities){
        updateAgentsCommission(opportunities.keySet());
    }

    public static void updateAgentsCommission(Set<Id> opportunitiesId){
        List<Sales_Agent__c> agents = [
            SELECT 
                Name, 
                (SELECT 
                    Rate__c,
                    Opportunity__r.Amount, 
                    Opportunity__r.StageName
                FROM Commissions__r) 
            FROM Sales_Agent__c
        ];

        Decimal totalPendingCommission;
        Decimal totalCompletedCommission;

        for(Sales_Agent__c agent : agents){
            totalPendingCommission = 0;
            totalCompletedCommission = 0;
            for(Commission__c commission : agent.Commissions__r){
                if(commission.Opportunity__r.StageName == 'Pending'){
                    totalPendingCommission += commission.Rate__c/100 * commission.Opportunity__r.Amount;
                } else if(commission.Opportunity__r.StageName == 'Completed Won'){
                    totalCompletedCommission += commission.Rate__c/100 * commission.Opportunity__r.Amount;
                }
            }
            agent.Pending_Commission_Amount__c = totalPendingCommission;
            agent.Completed_Commission_Amount__c = totalCompletedCommission;
        }

        update agents;
    }
}