force-app/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <displayFormat>COM-{00000}</displayFormat>
        <label>Commission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Sales_Agent__c.field-meta.xml
<CustomField>
    <fullName>Sales_Agent__c</fullName>
    <label>Sales Agent</label>
    <referenceTo>Sales_Agent__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Agent__c/Sales_Agent__c.object-meta.xml
<CustomObject>
    <label>Sales Agent</label>
    <nameField>
        <label>Sales Agent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CommissionTriggerHelper.cls
public with sharing class CommissionTriggerHelper {

    private static Set<Id> getOpportunitiesId(List<Commission__c> commissions){
        Set<Id> opportunitiesId = new Set<Id>();
        for(Commission__c commission : commissions){
            opportunitiesId.add(commission.Opportunity__c);
        }
        return opportunitiesId;
    }

    public static void validateTotalRateAmount(List<Commission__c> commissions){
        Set<Id> opportunitiesId = getOpportunitiesId(commissions);
    
        List<aggregateResult> results = [
            SELECT 
                SUM(Rate__c) totalRate, 
                Opportunity__c
            FROM Commission__c 
            WHERE Opportunity__c IN : opportunitiesId
            GROUP BY Opportunity__c
            HAVING SUM(Rate__c) > 100
        ];

        for (aggregateResult result : results){
            for (Commission__c commission : commissions){
                if (result.get('Opportunity__c') == commission.Opportunity__c){
                    commission.addError('The sum of all rates from this opportunity exceeds 100%');
                }
            }
        }
    }

    public static void validateDuplicates(List<Commission__c> commissions){
        Set<Id> opportunitiesId = getOpportunitiesId(commissions);
    
        List<aggregateResult> results = [
            SELECT 
                COUNT(Id),
                Opportunity__c,
                Sales_Agent__c
            FROM Commission__c
            WHERE Opportunity__c IN : opportunitiesId
            GROUP BY Opportunity__c, Sales_Agent__c
            HAVING COUNT(Id) > 1
        ];

        for (aggregateResult result : results){
            for (Commission__c commission : commissions){
                if (result.get('Opportunity__c') == commission.Opportunity__c && result.get('Sales_Agent__c') == commission.Sales_Agent__c){
                    commission.addError('Agent can\'t be added twice on the same opportunity');
                }
            }
        }
    }

    public static void updateAgentsCommission(List<Commission__c> commissions){
        OpportunityTriggerHelper.OpportunityTriggerHelper(getOpportunitiesId(commissions));
    }
}